### ISSUE TITLE
Credential mapping to appName/hostname pair

### ISSUE THREAD

**Issue by kortemik** [teragrep/lsh_01#16]
**Description**
currently only one is supported, however different credentials usually mean different streams (appName/hostname pairs)

**Use case or motivation behind the feature request**
different streams should be separated from each other, currently this is only possible by running multiple instances and routing to them with Authorization http header 

**Related issues**

**Additional context**

**Comment by kortemik** [comment]
perhaps use https://github.com/teragrep/jai_02/ as a lookup store for allowed key:value pairs.

**Comment by StrongestNumber9** [comment]
Implemented by #37

**Comment by kortemik** [comment]
duplicate of #36
