### ISSUE TITLE
Implement status/healthcheck endpoint

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/lsh_01#26]
**Description**

Allow status/healthcheck endpoint

**Use case or motivation behind the feature request**

Currently ANY http request will cause an event so implementing a status/healthcheck endpoint will allow us to monitor health and status

**Related issues**

**Additional context**

**Comment by kortemik** [comment]
It might be preferable to allow specifying a path into config that returns 200 but no event will be generated from such a path. Path is available in:
```
formattedHeaders.put("request_path", req.uri());
```

**Comment by StrongestNumber9** [comment]
#30 has configurable healthcheck support and some structural support for other internal endpoints. Decided to not include token checks for healthcheck endpoint for now as the path itself can act as a token like `/healthcheck?token=somesecrethere`
