### ISSUE TITLE
json_batch not supported

### ISSUE THREAD

**Issue by kortemik** [teragrep/lsh_01#75]
**Describe the bug**
json_batch not supported. current feature supports regex splitting but not json compatible array  splitting.

**Expected behavior**
configuration should let decide if regex or json based processing is in use.

**How to reproduce**

**Screenshots**

**Software version**
3.2.1

**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-http.html#plugins-outputs-http-format

```
[
{"a": 1},
{"b": 2}
]
```

**Comment by 51-code** [comment]
Refactored Payload objects and created end to end unit tests for the json_array splitType.

**Comment by 51-code** [comment]
There was some difficulties with getting the JSON objects as Strings. The in-built toString() function in Jakarta takes out any whitespace in the input. However, this was assessed to be okay, and the implementation will continue using the toString() function.

**Comment by 51-code** [comment]
Draft PR done, assistance needed for a minor design issue.

**Comment by 51-code** [comment]
Adding new configuration options for this functionality brought up the problem with the current configuration objects. I opened a new issue 
* #78 

about them. The new configuration options are already using this new style which is explained in the issue.
